### ISSUE TITLE
regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by zhou94** [antvis/XFlow#114]
### Describe the bug

xflow 1.0.30
vite 2.7.2
使用报错 regeneratorRuntime is not defined

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

use vite

### Expected behavior

组件库的打包问题 希望能处理下 

### Platform

- OS: [e.g. macOS, Windows, Linux] macOS
- Browser: [e.g. Chrome, Safari, Firefox] Chrome
- Version: [e.g. 91.1]97

**Comment by zhou94** [comment]
ant-mobile同样问题 可参照 https://github.com/ant-design/ant-design-mobile/issues/4675

**Comment by zhou94** [comment]
[demo.zip](https://github.com/antvis/XFlow/files/8114811/demo.zip)
这个最新的demo  显式只加了antd @ant-design/icons @antv/xflow三个依赖
dev 和 build之后还是报错 regeneratorRuntime is not defined

**Comment by BroKun** [comment]
https://github.com/umijs/mana/issues/6 升级 mana-common 到 0.3.1 版本可以解决问题。
