### ISSUE TITLE
FlowchartFormPanel 方便透传一下getCustomRenderComponent 及 其他配置选项

### ISSUE THREAD

**Issue by qq296565890** [antvis/XFlow#115]
### 描述你想申请的功能

想用FlowchartFormPanel的同时还想用JsonSchemaForm的自定义功能
![image](https://user-images.githubusercontent.com/26108264/150510217-9215e6e6-0ab3-4d15-afc6-75662559eea4.png)

目前采用CustomPanel实现了
[参考1](https://xflow.antv.vision/docs/tutorial/solutions/flow  )
[参考2](https://xflow.antv.vision/docs/tutorial-ext-components/workspace-panel)
```
<CustomPanel
            canvasScaleToolbarProps={{ position: { left: -32, top: 180 } }}
            position={{ top: 40, bottom: 0, right: 0, width: 400 }}
            targetType={['node', 'canvas']}
            formSchemaService={NsJsonForm.formSchemaService}
            // formValueUpdateService={NsJsonForm.formValueUpdateService}
            getCustomRenderComponent={NsJsonForm.getCustomRenderComponent} />
```
CustomPanel实现【参考了FlowchartFormPanel的实现】
```
const __rest = (this && this.__rest) || function (s, e) {
  const t = {};
  for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
    t[p] = s[p];
  if (s != null && typeof Object.getOwnPropertySymbols === "function")
    for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
      if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
        t[p[i]] = s[p[i]];
    }
  return t;
};
import React, { useState } from 'react';
import { DoubleRightOutlined, DoubleLeftOutlined } from '@ant-design/icons';
import { CanvasScaleToolbar, JsonSchemaForm, WorkspacePanel } from '@antv/xflow';
// import { JsonSchemaForm } from '../canvas-json-schema-form';
// import { WorkspacePanel } from '../base-panel';
// import { defaultFormSchemaService } from './form-schema-service';
// import { defaultControlMapService } from './control-map-service';
export const CONTAINER_CLASS = 'xflow-editor-panel-collpase';
export const CustomPanel = props => {
  const { defaultControlMapService, defaultFormSchemaService } = props
  const [collpased, setCollpased] = useState(false);
  const { canvasScaleToolbarProps, controlMapService = defaultControlMapService, formSchemaService = defaultFormSchemaService, position = { width: 240, top: 0, bottom: 0, right: 0 }, show = true } = props, rest = __rest(props, ["controlMapService", "formSchemaService", "position", "show"]);
  if (!show) {
    return null;
  }
  const { width = 200, right } = position;
  return (React.createElement(WorkspacePanel, { className: CONTAINER_CLASS, position: Object.assign(Object.assign({}, position), { right: !collpased ? right : -width }) },
    React.createElement("div", { className: `${CONTAINER_CLASS}-wrapper` },
      React.createElement(JsonSchemaForm,
        Object.assign({
          argetType: ['node', 'edge', 'canvas', 'group'],
          controlMapService: controlMapService,
          formSchemaService: formSchemaService,
          position: Object.assign(Object.assign({}, position), { top: 0 }),
          prefixClz: "xflow-form-editor"
        },
          rest)),
      React.createElement(CanvasScaleToolbar, {
        ...canvasScaleToolbarProps
      }),
      // React.createElement(CanvasMiniMap, Object.assign({
      //   position: { left: 0, top: 88 },
      //   // minimapOptions: { width: 200, height: 120 }
      // })),
      React.createElement("div", {
        className: `${CONTAINER_CLASS}-icon`, style: {
          top: 21,
          left: !collpased ? -10 : -20,
          borderRadius: !collpased ? '50%' : '50% 0 0  50%',
          borderRight: !collpased ? '' : 'none',
        }, onClick: () => {
          setCollpased(!collpased);
        }
      }, collpased ? React.createElement(DoubleLeftOutlined, null) : React.createElement(DoubleRightOutlined, null)))));
};
//# sourceMappingURL=form-panel.js.map
```

多实例使用如钉钉审批流
![image](https://user-images.githubusercontent.com/26108264/150511494-ea3b9919-6147-4748-8e38-9cb696e66410.png)

### 描述你想要的解决方案

统一的用户体验
统一的实现方式
尽量做到高度自定义

### 描述你所考虑的替代方案

暂无

### 屏幕截图或视频

https://user-images.githubusercontent.com/26108264/150511960-8fd6d996-d3fe-4a27-ab50-9704acedb96b.mp4

**Comment by lxfu1** [comment]
目前是支持自兴义的，看下[自定义表单](https://charts.ant.design/zh/examples/flowchart/basic#custom-form)，xflow 里面用法一样。

**Comment by qq296565890** [comment]
> 目前是支持自兴义的，看下[自定义表单](https://charts.ant.design/zh/examples/flowchart/basic#custom-form)，xflow 里面用法一样。

谢谢您的解答，但我的项目需要嵌入[Formily](https://formilyjs.org/zh-CN/guide)表单设计器的设计成果，现有的功能未能满足我的需求，还请亲帮忙开放一下这个功能，再次对您表示感谢！

**Comment by qq296565890** [comment]
> 目前 getCustomRenderComponent 也是支持的（但会有类型错误提示），你可以试下是否满足需求，类型错误随后会解掉。
> 
> ```tsx
> const getCustomRenderComponent = (targetType, targetData) => {
>   if (targetType === 'node') {
>     return () => (
>       <div className="custom-form-component"> node: {targetData?.label} custom componnet </div>
>     )
>   }
>   if (targetType === 'canvas') {
>     return () => <div className="custom-form-component"> canvas custom componnet </div>
>   }
> 
>   return null
> }
> 
> <FlowchartFormPanel
>     show={true}
>     position={{ width: 200, top: 40, bottom: 0, right: 0 }}
>     getCustomRenderComponent={getCustomRenderComponent}
>   />
> ```

> 非常感谢亲能帮助我解决难题。这已经可以满足我的需求。示例代码如下：
>
>```tsx
> // #region getCustomRenderComponent定义
> export const getCustomRenderComponent: NsJsonSchemaForm.ICustomRender = (
>      targetType,
>      targetData,
>      // commandService // 暂时不支持此参数，如果以后能支持就更好了
>    ) => {
>      const commandService = useXFlowApp();
>      const updateNode = (node: NsGraph.INodeConfig) => {
>        return commandService.executeCommand<NsNodeCmd.UpdateNode.IArgs>(
>          XFlowNodeCommands.UPDATE_NODE.id,
>          { nodeConfig: node },
>        )
>      }
> ......
> // #endregion
> // 我期望FlowchartFormPanel 能够像 JsonSchemaForm 一样使用。
> 
> // #region 使用方式
> <FlowchartFormPanel
>     show={true}
>     position={{ width: 400, top: 40, bottom: 0, right: 0 }}
>     getCustomRenderComponent={NsJsonForm.getCustomRenderComponent}
> />
> // #endregion
> 
> 
>```
>  更多使用细节请参考：
>  [CustomPanel](https://xflow.antv.vision/docs/tutorial-ext-components/workspace-panel) 
>  [自定义渲染getCustomRenderComponent](https://xflow.antv.vision/docs/tutorial-ext-components/canvas-config-form#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93-getcustomrendercomponent)
![image](https://user-images.githubusercontent.com/26108264/154392421-54740be9-946d-476f-b1d5-d0ef1320344c.png)
