### ISSUE TITLE
XFlow 组件使用style属性无效果，className可以

### ISSUE THREAD

**Issue by serializedowen** [antvis/XFlow#116]
### Describe the bug

XFlow 组件使用style属性无效果，className可以

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

    <XFlow
      onLoad={onLoad}
      graphLayout={{ layoutType: 'er', layoutOptions: {} }}
      style={{ height: '100%' }}   //无效果
      className="er-xflow-container"
    >
      <XFlowCanvas config={graphConfig}>
        <CanvasMiniMap nodeFillColor="#ced4de" minimapOptions={{}} />
      </XFlowCanvas>
    </XFlow>

### Expected behavior

有效果

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lyn-boyu** [comment]
近期fix
