### ISSUE TITLE
Angular可以使用吗？

### ISSUE THREAD

**Issue by huajian123** [antvis/XFlow#118]
### 描述你想申请的功能

Angular可以使用吗？

### 描述你想要的解决方案

Angular可以使用吗？

### 描述你所考虑的替代方案

Angular可以使用吗？

**Comment by boskiv** [comment]
@huajian123  did you find a n Angular implementation ?

**Comment by huajian123** [comment]
@boskiv  No, I implemented a simple , online demo http://124.71.128.53:8081/#/default/feat/flow/flow-chat ,
sourcecode https://github.com/huajian123/ng-ant-admin/tree/master/src/app/pages/feat/flow/flow-chat
