### ISSUE TITLE
jsonForm 配置式表单自定义渲染 getCustomRenderComponent copy 到本地 ts 报错

### ISSUE THREAD

**Issue by xixinglong** [antvis/XFlow#122]
### 问题描述

这边采用create-react-app Typescript   + 线上demo 测试  本地报错无法运行
![lQLPDhsiaZikZe3NAVDNBb-wTHcG7kfmm8UCCQ366MCMAA_1471_336](https://user-images.githubusercontent.com/25213883/153165609-5e1724a0-59d3-4eb2-87e4-99ef4bd18d69.png)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

1.使用create-react-app Typescript 搭建demo
2.安装antd 依赖配置
3.将官网示例复制到本地，运行报错
![Uploading lQLPDhsiaZikZe3NAVDNBb-wTHcG7kfmm8UCCQ366MCMAA_1471_336.png…]()

### 预期行为

![Uploading lQLPDhsiaZDkwX_NAgnNBa-wW59sH2SDGIcCCQ3uQsCpAA_1455_521.png…]()

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Chrome]
- XFlow 版本: [1.0.3 ... ]
![lQLPDhsiadkD5SrNAdLNAfKwQLXFxCNONwECCQ5kvcCqAA_498_466](https://user-images.githubusercontent.com/25213883/153166067-88212296-e556-46ae-aa37-711bd9085636.png)

**Comment by lyn-boyu** [comment]
try walk-around:  tsconfig.json > compilerOptions > "strict": false 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
```
