### ISSUE TITLE
Toobar 自定义渲染 render 提供 commandService

### ISSUE THREAD

**Issue by draco-china** [antvis/XFlow#134]
### Describe the feature you'd like to request

工具栏的自定义 render时，对 graph 操作时没有对应的 API， 只能通过全局获取 grpah 操作

### Describe the solution you'd like

Toobar 自定义渲染 render 提供 commandService 或者 graph 对象

### Describe alternatives you've considered

目前是通过自定义组件去全局获取全局对象来实现自定义操作

### Screenshots or Videos

![lALPJwY7RhZGQgfNAunNAvA_752_745](https://user-images.githubusercontent.com/22271474/154389784-0a17d61c-a665-4f9f-8d59-74f78fb1f70b.png)

**Comment by promise6512** [comment]
您好，这个问题我已经提交了相关 pr https://github.com/antvis/XFlow/pull/193。
后续可以在 props 里面拿到 CommandService 和 ModelService

**Comment by draco-china** [comment]
=

> 你好，这个问题我已经提交了相关的PR [https://github.com/antvis/XFlow/pull/193。](https://github.com/antvis/XFlow/pull/193%E3%80%82) 可以在道具里面拿到 CommandService 和 ModelService
> 
> ```
> render: (props) => {
>     const { modelService, commandService } = props;
>     return <div>我是定义 render item<div/>
> }
> ```

已经更新到最新版本，并没有看到相关实现呢
