### ISSUE TITLE
XFlow DAG解决方案port样式

### ISSUE THREAD

**Issue by lishaopeng221** [antvis/XFlow#136]
### 描述你想申请的功能

当一个port有多个连接线以后，我删除其中一条，样式就变成了没有连接的状态了
删除连线时校验是否还有输入

### 描述你想要的解决方案

删除连线时校验是否还有输入，有就不改变样式，没有就改变样式

### 描述你所考虑的替代方案

删除连线时校验是否还有输入，有就不改变样式，没有就改变样式

### 屏幕截图或视频

![lALPJvDqTmZyf-nNAcjNAgQ_516_456](https://user-images.githubusercontent.com/25917470/155049108-29f0490d-3681-41f9-ae0b-3968033bdae9.png)

**Comment by lyn-boyu** [comment]
在hooks里实现一下？
https://github.com/antvis/XFlow/blob/634d925123c46b7bf43dfc81e2087f18808bdc27/packages/xflow-extension/src/canvas-dag-extension/contributions/dag.tsx#L297

**Comment by lishaopeng221** [comment]
功能实现了。


      hooks.delEdge.registerHook({
        name: 'get edge config from backend api',
        handler: async (args, handler) => {
          if (!handler) {
            return
          }
          const result: NsEdgeCmd.DelEdge.IResult = await handler(args)
          const {targetCell, targetPortId} = result
          const {commandService} = args
          if (targetCell && targetCell.isNode() && targetPortId) {
            if (commandService) {
              await commandService.executeCommand<NsGraphCmd.SaveGraphData.IArgs>(
                XFlowGraphCommands.SAVE_GRAPH_DATA.id, {
                  saveGraphDataService: async (m, graph) => {
                    if (graph?.edges?.filter(edge => edge?.target === targetCell?.id).length === 0) {
                      targetCell.setPortProp(targetPortId, 'connected', false)
                    }
                    return graph
                  },
                },)
            }
          }
        },
      }),
