### ISSUE TITLE
添加监听事件，移动或添加node时，两个node相距到达一定数值时。显示可以连线，鼠标抬起，添加连线

### ISSUE THREAD

**Issue by lishaopeng221** [antvis/XFlow#137]
### 描述你想申请的功能

添加监听事件，移动或添加node时，两个node相距到达一定数值时。显示可以连线，鼠标抬起，添加连线

### 描述你想要的解决方案

添加监听事件，移动或添加node时，两个node相距到达一定数值时。显示可以连线，鼠标抬起，添加连线

### 描述你所考虑的替代方案

添加监听事件，移动或添加node时，两个node相距到达一定数值时。显示可以连线，鼠标抬起，添加连线

**Comment by lxfu1** [comment]
这不合理吧

**Comment by lishaopeng221** [comment]
我想要这样，移动节点时两个节点到一定距离，添加连线，距离变远时，删除连线

**Comment by lxfu1** [comment]
这种暂时不支持的

**Comment by lishaopeng221** [comment]
好的好的
