### ISSUE TITLE
提供支持BPMN扩展

### ISSUE THREAD

**Issue by yanxmd** [antvis/XFlow#161]
### 描述你想申请的功能

需要按照 BPMN 的规范来绘制流程图

### 描述你想要的解决方案

可以直接使用XFlow来绘制兼容 BPMN2.0 规范的流程

### 描述你所考虑的替代方案

可以直接使用XFlow来绘制兼容 BPMN2.0 规范的流程

**Comment by yanxmd** [comment]
创意版是什么？能提供链接入口吗？

**Comment by lxfu1** [comment]
feature：目前还没实现，后续版本会考虑。

**Comment by yanxmd** [comment]
hd

**Comment by yanxmd** [comment]
那目前通过自定义能实现吗

**Comment by lxfu1** [comment]
自定义节点加上合理的 canvasConfig 可以实现， https://github.com/antvis/XFlow/blob/master/packages/xflow-extension/src/flowchart-canvas/config-graph.tsx#L134

**Comment by yanxmd** [comment]
好的，谢谢
