### ISSUE TITLE
DAG解决方案希望提供自定义节点样式、点击边触发类似节点编辑属性的能力

### ISSUE THREAD

**Issue by topwood** [antvis/XFlow#17]
如果本身支持这样的能力，希望在文档中进一步说明~谢谢~

**Comment by lyn-boyu** [comment]
JsonSchemaForm组件上配置 targetType={['node', 'edge', 'canvas']}来实现
请参考：
https://xflow.antv.vision/docs/tutorial-ext-components/canvas-config-form#%E6%94%AF%E6%8C%81%E6%9B%B4%E5%A4%9A%E9%80%89%E4%B8%AD%E5%AF%B9%E8%B1%A1
