### ISSUE TITLE
graph-render command 中的顺序问题

### ISSUE THREAD

**Issue by zxc0328** [antvis/XFlow#174]
### Describe the feature you'd like to request

目前 graph-render  command 中 diff 之后的顺序是 add、delete、最后 update。

有一种场景，节点已经在画布中，但是是 visible:false 的状态。此时如果做一次数据更新，把节点置为  visible:true，并且再添加一条该节点的边，这个新加的边是不会展示的。因为 add 操作在最前面，add 的时候节点还是 visible:false 的状态，尚未更新，所以边也没有展示出来。这里有一个时序上的先后问题。

### Describe the solution you'd like

如果顺序是先 update 再 add 和 delete。是不是会更合理。因为 update 的对象肯定是之前就在画布上的。然后 update 的时候也不涉及后面 add 和 delete 的节点/边。因为边的 source 和 target 是不参与 update 的（如果变化了理论上 id 也应该变，就不是同一条边了）。

但 add 和 delete 的节点/边是会涉及现在在画布上的节点的。所以让这些节点先完成更新，之后再 add、delete 就会避免一些时序问题出现。

**Comment by promise6512** [comment]
您好，我最近刚开始维护 xflow，想请问一下您说的 visible 是什么意思，自定义的属性吗？
