### ISSUE TITLE
文档完善：元信息Meta概念没有描述清楚

### ISSUE THREAD

**Issue by topwood** [antvis/XFlow#18]
![image](https://user-images.githubusercontent.com/13791267/143213589-c9d5d572-70f3-452a-8b91-19d379c54f19.png)

https://xflow.antv.vision/docs/tutorial-core-components/xflow-component#%E6%A0%B8%E5%BF%83%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by lyn-boyu** [comment]
JsonSchemaForm组件上配置 targetType={['node', 'edge', 'canvas']}来实现 
请参考：
https://xflow.antv.vision/docs/tutorial-ext-components/canvas-config-form#%E6%94%AF%E6%8C%81%E6%9B%B4%E5%A4%9A%E9%80%89%E4%B8%AD%E5%AF%B9%E8%B1%A1

**Comment by lyn-boyu** [comment]
https://xflow.antv.vision/api/commands/graph-meta
