### ISSUE TITLE
编辑器全屏后 NodePanel 的Popover被XFlow chartCanvas遮挡了

### ISSUE THREAD

**Issue by qq296565890** [antvis/XFlow#184]
### 问题描述

两个问题，由于问题比较明显，就直接贴图了
![1646919829398_68F3955C-4FA3-4272-9725-19132DF62BF5](https://user-images.githubusercontent.com/26108264/157675326-1d3cb449-d3ba-44b3-aa3d-26dc5c68ce59.png)
![1646919730493_90E255CE-B361-4192-98E2-960900DBD90D](https://user-images.githubusercontent.com/26108264/157675371-95dec63e-b96e-42e5-b2d9-3e7d21f4465f.png)

### 重现链接

https://xflow.antv.vision/docs/tutorial/solutions/flow/

### 重现步骤

https://xflow.antv.vision/docs/tutorial/solutions/flow/

### 预期行为

https://xflow.antv.vision/docs/tutorial/solutions/flow/

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by promise6512** [comment]
这个是 antd 的 popover 组件挂载的问题，下个小版本会解决掉的～
