### ISSUE TITLE
group 子节点未正常显示在group中

### ISSUE THREAD

**Issue by arthur657834** [antvis/XFlow#185]
### 问题描述

group 子节点未正常显示在group中

### 重现链接

https://codesandbox.io/s/festive-benji-yh1xu0?file=/service.ts

### 重现步骤

1. 打开codesanbox地址
2. 修改service.ts，添加group配置

### 预期行为

group 子节点正常显示在group中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/9419700/157704825-7e55846c-1588-4529-8d19-1ff02b68251f.png)

**Comment by GageChan** [comment]
我也遇到了相同的问题，请问大佬解决了吗？
