### ISSUE TITLE
流程图，无法往画图面板上添加自定义图形

### ISSUE THREAD

**Issue by MrMengJ** [antvis/XFlow#195]
### Describe the bug

通过 `NodeCollapsePanel`  组件定义的自定义图形，无法往画图面板上添加

### Your Example Website or App

https://codesandbox.io/s/condescending-andras-5bcz4l

### Steps to Reproduce the Bug or Issue

无法往画图面板上添加自定义图形

### Expected behavior

期望可以往画图面板上添加自定义的图形

### Screenshots or Videos

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/26325346/158405480-b94ca72a-db21-4551-991d-9294c4ee9943.png">

报错代码位置
https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-core/src/command-contributions/node/node-add.ts#L159

### Platform

- OS:  macOS
- Browser:  Chrome
- Version:  99

### Additional context

通过调试发现在源代码处，是因为在`flowchart-canvas`组件里并未注册自定义的图形，导致往画图面板添加图形的时候根据 `renderKey` 找不到对应 `component`

https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-extension/src/flowchart-canvas/config-graph.tsx#L75

https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-extension/src/flowchart-node-panel/utils.tsx#L98

https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-core/src/command-contributions/node/node-add.ts#L159

**Comment by MrMengJ** [comment]
@lifesinger @RaoHai @linhuiw @rockdai

**Comment by hushaoqing** [comment]
[测试有效] 可以尝试使用 `useConfig` 注册，代替`FlowchartNodePanel`
https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-extension/src/flowchart-canvas/config-graph.tsx#L247

![image](https://user-images.githubusercontent.com/10289162/164437543-79f25365-0ef9-45dd-8dfd-d1f2c4e34433.png)

**Comment by MrMengJ** [comment]
> [测试有效] 可以尝试使用 `useConfig` 注册，代替`FlowchartNodePanel`
> 
> https://github.com/antvis/XFlow/blob/be80d8a0651993ad66e34266aea8f101c6531f72/packages/xflow-extension/src/flowchart-canvas/config-graph.tsx#L247
> 
> ![image](https://user-images.githubusercontent.com/10289162/164437543-79f25365-0ef9-45dd-8dfd-d1f2c4e34433.png)

谢谢，已经通过别的方式来实现啦
