### ISSUE TITLE
XFlow l流程解决中的 撤销功能

### ISSUE THREAD

**Issue by ayaayaayaai** [antvis/XFlow#197]
### 问题描述

XFlow 流程解决 菜单栏中的撤销功能不能实现 getGraphHistory() 找不到 

### 重现链接

https://codesandbox.io/s/old-river-cyc9ih?file=/config-toolbar.ts:2695-2710

### 重现步骤

1. 拖一个节点及报错

### 预期行为

撤销功能可以实现

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by promise6512** [comment]
画布撤销功能，我在 dev 分支里面实现了，你可以拉这个分支看一下咋写的～

**Comment by ayaayaayaai** [comment]
已解决

**Comment by azcdazq** [comment]
> 

请问怎么解决的

**Comment by ws2332332** [comment]
首先，我没有在楼上所说的dev分支上看到解决的方案，也许是我自己没看到而已。我看过x6的文档，在graph实例里可以拿到history对象。因此我将history通过meta透传。这可能是比较笨的方法，目前我只能这么做。
![image](https://user-images.githubusercontent.com/42539442/190107476-3c5d4752-9ec9-4068-9609-f38b384511de.png)
