### ISSUE TITLE
无法连续右键菜单

### ISSUE THREAD

**Issue by MrMengJ** [antvis/XFlow#229]
### 问题描述

现在在画图面板上鼠标右键出现菜单，但无法连续右键唤出菜单。在菜单已经唤出的情况下，必须先点击空白区域取消现在的菜单，再鼠标右键唤出菜单，体验不佳。

### 重现链接

https://xflow.antv.vision/docs/tutorial-ext-components/context-menu

### 重现步骤

1、画图面板右键唤出菜单
2、再次在画图面板上右键，无任何反应，原先唤出的菜单也不消失

### 预期行为

再次在画图面板上点击右键，希望取消原先的菜单，再唤出新的菜单

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- XFlow 版本: [1.0.41]

### 屏幕截图或视频（可选）

![context menu](https://user-images.githubusercontent.com/26325346/162861322-52c84dcf-86dd-4722-a9c9-5683ff9c4f73.gif)

**Comment by MrMengJ** [comment]
`not-stable`

**Comment by MrMengJ** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not-stale" to keep this issue open!
> 
> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [contribute](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the AntV community! 💪💯

**Comment by MrMengJ** [comment]
not-stable

**Comment by XenonPDash** [comment]
I meet this problem too. Is there any solution now?

**Comment by MrMengJ** [comment]
> I meet this problem too. Is there any solution now?

I modify the source code and maintaining myself

**Comment by Max-ChenFei** [comment]
@MrMengJ Hi, did you update to react 18?

**Comment by MrMengJ** [comment]
> @MrMengJ Hi, did you update to react 18?

No, I didn't
