### ISSUE TITLE
文档部分页面404

### ISSUE THREAD

**Issue by EasySimple** [antvis/XFlow#23]
1.仓库的README.MD中[XFlow 使用文档](https://xflow.antv.vision/zh/docs/tutorial-01/about)，控制台报错
GET https://xflow.antv.vision/zh/docs/tutorial-01/about 404，应该是配置的链接地址错误，或者部署资源不对。
![image](https://user-images.githubusercontent.com/53426682/144464572-825a33e2-ec03-471d-8b49-85d99030ad84.png)
2.点击使用文档网站左上角AntV logo或者点击XFlow进入文档首页https://xflow.antv.vision/，页面底部以下资源或者地址404
- 底部的4个纵列 产品首页链接地址、图标用例、使用文档、API文档 共16个地址全部含有undefined，导致跳转出错
![image](https://user-images.githubusercontent.com/53426682/144467294-e1bcff1a-67fb-4e32-b499-a8eca91067b2.png)
![image](https://user-images.githubusercontent.com/53426682/144467552-d4616da3-44f5-470a-9bc5-1c0544ffc837.png)
![image](https://user-images.githubusercontent.com/53426682/144467705-8bc78700-979e-4fe7-8aa2-b5536314f7eb.png)

**Comment by lyn-boyu** [comment]
thanks for your report. let me check it out
