### ISSUE TITLE
registerCustomNode 缺少参数

### ISSUE THREAD

**Issue by arthur657834** [antvis/XFlow#233]
### 问题描述

registerCustomNode需要必填参数：

函数定义：
export const registerCustomNode = (
  panelConfigs: IRegisterNode | IRegisterNode[],
)

错误行:

export const setNodeRender = config => {
  registerCustomNode()

文件路径: https://github.com/antvis/XFlow/blob/master/packages/xflow-extension/src/flowchart-node-panel/utils.tsx

### 重现链接

https://github.com/antvis/XFlow/blob/master/packages/xflow-extension/src/flowchart-node-panel/utils.tsx

### 重现步骤

1. 文件utils.tsx 第114行registerCustomNode缺少参数

### 预期行为

添加registerCustomNode参数

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by lyn-boyu** [comment]
thanks for your report we will fix this issue ASAP

**Comment by lyn-boyu** [comment]
https://github.com/antvis/XFlow/pull/235
