### ISSUE TITLE
更新graphData时报错edge is not exist

### ISSUE THREAD

**Issue by cjmafei** [antvis/XFlow#255]
### 问题描述

更新graphData时控制台报错edge is not exist

### 重现链接

https://codesandbox.io/s/hopeful-haibt-nlzzu8?file=/App.tsx

### 重现步骤

1.进入页面
2.打开控制台
3.点击左上角切换数据源
4.观察控制台

### 预期行为

无报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by GeraltX** [comment]
遇到同样的问题
