### ISSUE TITLE
流程图上的一次操作，需要执行两次或者多次撤销动作才能回到上一个状态

### ISSUE THREAD

**Issue by MrMengJ** [antvis/XFlow#270]
### 问题描述

流程图上对图形的一次操作，需要执行两次或者多次撤销动作才能回到上一个状态

### 重现链接

https://codesandbox.io/s/ysquyr

### 重现步骤

1、进入页面，添加一个图形
2、移动或者放大这个图形，ctrl+z 撤销，需要操作两次才能撤销回去

### 预期行为

任何操作都只需要撤销一次就能撤销到上一次的状态

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- XFlow 版本: [1.0.48]

### 补充说明（可选）

经过排查，是因为XFlow会将图形的所有数据存放在[data](https://x6.antv.vision/zh/docs/api/model/cell#data)中，在每次更新图形时（比如 移动，放大缩小）会将图形最新的数据再次同步到data中，导致X6记录了至少两次的入栈，一次是真实操作改变数据的入栈，一次是更新data导致的入栈，这就导致了需要撤销两次才能撤回到原来的状态。

**Comment by MrMengJ** [comment]
unstable

**Comment by ws2332332** [comment]
可以过滤一些历史操作

**Comment by ws2332332** [comment]
可以设置条件，过滤一些操作

**Comment by MrMengJ** [comment]
> 可以设置条件，过滤一些操作 ![image](https://user-images.githubusercontent.com/42539442/190106366-c0588bab-8366-4430-8c7b-6af92c464cca.png)

感谢回复，已将在项目上这样用上了，但我认为这是xflow设计上的问题
