### ISSUE TITLE
在一个页面使用两次NodeCollapsePanel，获取两组不同的数据并展示

### ISSUE THREAD

**Issue by ayaayaayaai** [antvis/XFlow#279]
### 问题描述

在一个页面中，使用两个NodeCollapsePanel,获取不同的数据，结果只有一个NodeCollapsePanel获取到数据并展示，更改graphMeta，modelService没有效果****

### 重现链接

https://codesandbox.io/s/ji-chu-shi-yong-forked-k0qfdf?file=/dnd-panel-config.tsx

### 重现步骤

1.切换tab能够展示不同的节点数据
2.切换tab只能展示先打开的tab里的NodeCollapsePanel中的数据
3.另一个tab中使用该组件获得空数组

### 预期行为

期望两个NodeCollapsePanel能展示不同数据

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/45863356/173807505-d829de39-bdb3-4427-a6e1-1cb9605765c4.png)
![image](https://user-images.githubusercontent.com/45863356/173807725-a530cab2-3393-442f-bb07-05d092b9ec71.png)

### 补充说明（可选）

需要通过切换tab展示不同的节点数据

**Comment by ayaayaayaai** [comment]
多个相同组件使用同一个Model导致

**Comment by GageChan** [comment]
> 多个相同组件使用同一个Model导致

请问大佬有什么方法解决吗？

**Comment by zhangjiana** [comment]
请问解决了吗？
