### ISSUE TITLE
1.0.8反显报错

### ISSUE THREAD

**Issue by xuxingeren** [antvis/XFlow#28]
按照官方示例[链接](https://codesandbox.io/s/xoxxo)，发现升级为"@antv/xflow": "1.0.8",这个例子中的graphData反显会报错，且反显不了，降级为"@antv/xflow": "1.0.7"后正常显示
错误抛出为
```
Cannot read properties of undefined (reading 'dagre')
```

**Comment by lyn-boyu** [comment]
请升级到1.0.10
详见：https://github.com/antvis/XFlow/pull/31
