### ISSUE TITLE
拖拽面板 NodeDndPanel 节点 只能展示两层，怎么展示多层级，拖拽它的子节点 

### ISSUE THREAD

**Issue by wendaoshuai66** [antvis/XFlow#301]
### Describe the feature you'd like to request

功能描述

如图所示，只能加两层数据

![image](https://user-images.githubusercontent.com/31531781/181679551-48d99553-0d62-4a1e-b663-cdbab4312784.png)

### Describe the solution you'd like

期望解决方案

期望能添加多层级

### Describe alternatives you've considered

是否可以将树状组件替换  拖拽面板 NodeDndPanel 节点

**Comment by 173974319** [comment]
git上把源码拉下来找到NodeCollapsePanel的组件，自己根据业务需求重构一下
