### ISSUE TITLE
我按照文档中一步步来，根本运行不起来 ，报错信息如图所示

### ISSUE THREAD

**Issue by PieDi** [antvis/XFlow#307]
### 问题描述

![image](https://user-images.githubusercontent.com/19202314/183621891-f0cb414d-a557-4d09-8330-c165d0bc4de3.png)

我是把  https://xflow.antv.vision/zh-CN/docs/tutorial/intro/getting-started  此处示例代码拷贝下来本地运行
![image](https://user-images.githubusercontent.com/19202314/183622360-72131f0f-e9cc-47b4-b275-7fcf25ad6109.png)

### 重现链接

无

### 重现步骤

![image](https://user-images.githubusercontent.com/19202314/183622053-f10be849-b002-434b-aa25-59dcffc0b824.png)

### 预期行为

期待能正常运行

### 平台

- 操作系统: [macOS, React]
- 网页浏览器: [Google Chrome]
- XFlow 版本: [1.0. 50]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/19202314/183622103-538a0721-2764-4db6-8fae-d54adb464423.png)
![image](https://user-images.githubusercontent.com/19202314/183622191-a916b1d7-9ac1-4c68-9c61-9fb9c06799dd.png)

**Comment by dailybudushu** [comment]
一样的问题，这个项目目前还有人维护嘛？连基础demo都跑不起来？

**Comment by dailybudushu** [comment]
把react改成17能跑，参考：https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc
