### ISSUE TITLE
无法设置copied节点属性

### ISSUE THREAD

**Issue by hiwangman** [antvis/XFlow#32]
### Expected Behavior
copied的节点也可以设置内容，样式属性

### Current Behavior
copied的节点设置属性时报错

### Steps To Reproduce

https://xflow.antv.vision/~demos/flow-demos

1. 随便拖动一个组件至画布。
2. 然后复制、粘贴一个copied的节点
3. 修改copied节点属性就会出现以下报错信息

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
node-update.js:42 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setData')
    at UpdateNodeCommand.<anonymous> (node-update.js:42)
    at Generator.next (<anonymous>)
    at fulfilled (node-update.js:13)
```

</p></details>

### Your Environment

- antv/xflow": [1.0.10]
- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by lxfu1** [comment]
加个 hooks ，参考 https://github.com/antvis/XFlow/pull/47
