### ISSUE TITLE
流程图解决方案中无法禁止节点拖拽

### ISSUE THREAD

**Issue by PeterYang0** [antvis/XFlow#328]
### Describe the bug

流程图解决方案中在FlowchartCanvas中配置了setX6Config设置nodeMovable: false,不生效

### Your Example Website or App

https://codesandbox.io/s/wonderful-nobel-z4e2k9?file=/App.tsx

### Steps to Reproduce the Bug or Issue

流程图解决方案中在FlowchartCanvas中配置了setX6Config设置nodeMovable: false,不生效

### Expected behavior

作为用户，我期望在流程图解决方案中在FlowchartCanvas中配置了setX6Config设置nodeMovable: false,可以禁用节点的拖拽

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by westzmg** [comment]
这样设置可以解决问题：
config.setX6Config({
    interacting: ()=>false
})

详情配置见
https://x6.antv.vision/zh/docs/tutorial/basic/interacting#%E5%AE%9A%E5%88%B6%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA
