### ISSUE TITLE
x6 xflow 流程图是否支持导出满足bpmn规范的xml数据格式？

### ISSUE THREAD

**Issue by codexul** [antvis/XFlow#339]
### Describe the feature you'd like to request

我们正在考虑替换现有产品方案，目前是基于 bpmn.js实现的画布工艺流程设计，但碍于bpmn.js框架不够完善的api，很多业务场景实现有局限性，考虑新2.0版本系统使用 x6 xflow替换掉，但需要支持xml数据格式，因为目前的项目后端是解析xml数据，业务场景如图：

![image](https://user-images.githubusercontent.com/97442161/209808681-08d2b364-4214-4d3a-9545-02931d7d12ba.png)

### Describe the solution you'd like

希望基于x6 xflow流程设计方案，流程图可支持bpmn规范导出xml数据格式

### Describe alternatives you've considered

希望基于x6 xflow流程设计方案，流程图可支持bpmn规范导出xml数据格式

**Comment by itthegirlOy** [comment]
提问者写的挺清楚的，你们是看不懂中文吗？这是个新需求，应该不需要复现问题的流程吧

**Comment by Valen-C12** [comment]
可以看看LogicFlow，专门写了支持bpmn
https://docs.logic-flow.cn/docs/#/zh/guide/extension/bpmn-element
