### ISSUE TITLE
XFlow XFlowCanvas XFlowAppProvider lack feature 'children'

### ISSUE THREAD

**Issue by whsqjss** [antvis/XFlow#341]
### Describe the bug
![xflow](https://user-images.githubusercontent.com/35548533/210477814-e3c7a5b3-0d05-4835-904c-e577bf2537f6.png)

### Your Example Website or App

has no web site

### Steps to Reproduce the Bug or Issue

typescript error remind

### Expected behavior

to fix this?

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [108.0.5359.124]

**Comment by mannix-lei** [comment]
so how to fix this problem? I got this problem too.
