### ISSUE TITLE
fix: 点击缩放工具栏中的全屏按钮后，流程图全屏后，背景色由白色变为黑色

### ISSUE THREAD

**Issue by stone-lyl** [antvis/XFlow#352]
### 问题描述

点击缩放工具栏中的全屏按钮后，流程图全屏后，背景色由白色变为黑色

### 重现链接

https://xflow.antv.vision/~demos/canvas-scale-toolbar-demos

### 重现步骤

点击缩放工具栏中的全屏按钮后，流程图全屏后，背景色由白色变为黑色

### 预期行为

点击缩放工具栏中的全屏按钮后，流程图全屏后，背景仍为白色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]: macOS
- 网页浏览器: [Google Chrome, Safari, Firefox]: Google
- XFlow 版本: [1.28.2 ... ]:   本地  "@antv/xflow": "^1.0.53"， 线上demo 也可以复现，线上应该是最新版本

### 屏幕截图或视频（可选）

![xflow-full-screen](https://user-images.githubusercontent.com/20497176/218912276-4bc6fee8-3131-4a49-bcd7-cb32b1838dc4.gif)

**Comment by stone-lyl** [comment]
暂时通过写死背景色： `style={{ backgroundColor: '#fff'}}` 进行修复了。
如果项目还在维护的话，麻烦关注一下问题。❀

**Comment by Max-ChenFei** [comment]
@stone-lyl 请问你是使用react 17吗？
