### ISSUE TITLE
react18下类型“IntrinsicAttributes & IFlowchartGraphProps”上不存在属性“children”

### ISSUE THREAD

**Issue by shmjiao** [antvis/XFlow#353]
### 问题描述

React18去掉了props的children，现引入typescript的react18版本后，XFlow报错：类型“IntrinsicAttributes & IFlowchartGraphProps”上不存在属性“children”，需要更新下

### 重现链接

https://codesandbox.io/s/ji-chu-shi-yong-fang-fa-forked-3jjees?file=/App.tsx

### 重现步骤

（用如上沙盒添加types/react:18.0.28依赖即可）
1、引入Xflow，"@types/react": "18.0.28",
2、在XFlow中加入children，
 <XFlow
                className={styles['flow-user-custom-clz']}
                commandConfig={commandConfig}
                onLoad={onLoad}
                meta={meta}>
                <Save id={flow_id} flowDesignId={flow_design_id} />
                <FlowchartExtension />
……
3、引入 "@types/react": "18.0.28", "@types/react-dom": "18.0.11", "react": "18.2.0","react-dom": "18.2.0",
4、报错类型“IntrinsicAttributes & IFlowchartGraphProps”上不存在属性“children”

### 预期行为

不报错，兼容React18及ts

### 平台

- 操作系统: [Windows, Linux, React18]
        "@types/react": "18.0.28", "@types/react-dom": "18.0.11", "react": "18.2.0","react-dom": "18.2.0",
- 网页浏览器: [Google Chrome]
- XFlow 版本:  "@antv/x6": "^1.32.11",
        "@antv/x6-react-shape": "^1.6.1",
        "@antv/xflow": "^1.0.53",
        "@antv/xflow-core": "^1.0.53",

**Comment by johnninja** [comment]
有结果了？

**Comment by TSjianjiao** [comment]
建一个d.ts文件，覆写react的定义
```
declare module 'react' {
  interface FunctionComponent<P = {}> {
    (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
  }
}
````

**Comment by shmjiao** [comment]
你好，最后我用下方语句屏蔽掉了
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

**Comment by shmjiao** [comment]
> 建一个d.ts文件，覆写react的定义
> 
> ```
> declare module 'react' {
>   interface FunctionComponent<P = {}> {
>     (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
>   }
> }
> ```

谢谢

**Comment by ShenHongFei** [comment]
It's not fixed
