### ISSUE TITLE
DAG 图编辑 Node 只有单个输出桩情况下，输出桩无法拖动连线

### ISSUE THREAD

**Issue by pzpupu** [antvis/XFlow#359]
### Describe the bug

DAG 图编辑在定义 Node 只有单个输出桩情况下，输出桩无法拖动连线到其它Node的输入桩

### Your Example Website or App

https://codesandbox.io/s/sharp-sara-4wc4hg

### Steps to Reproduce the Bug or Issue

1. 拖动 “算法节点-1” 输出桩 连接到“算法节点-2”、“算法节点-3”、“算法节点-4” 输入桩

### Expected behavior

我期望Node只有单个输出柱的情况下，也可以进行拖动连接到其它的输入柱

### Screenshots or Videos

![iShot_2023-03-06_15 11 37](https://user-images.githubusercontent.com/96196073/223043694-8aaf34d4-2aab-4a09-86a1-96d6a7807b0e.gif)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by zyfass** [comment]
@pzpupu  有解决方案不
