### ISSUE TITLE
或许会有vue的版本吗

### ISSUE THREAD

**Issue by mollyhappy** [antvis/XFlow#367]
### 描述你想申请的功能

会有vue版本实现的版本吗

### 描述你想要的解决方案

会有vue版本实现的版本吗

### 描述你所考虑的替代方案

会有vue版本实现的版本吗

**Comment by RRDAWLX** [comment]
![image](https://user-images.githubusercontent.com/8463678/227615121-86b96729-49e9-4b0f-a8ae-8dbf241cdf71.png)

![image](https://user-images.githubusercontent.com/8463678/227614915-32f9613d-60ab-4a3b-96f4-4f3961b7bcdb.png)

或许很难有了🤣

**Comment by mollyhappy** [comment]
>这个交互感觉做的还不错的，可惜没有vue的版本，难过
