### ISSUE TITLE
ios手机任何浏览器，查看xflow自定义节点布局，自定义节点都会跑到屏幕左上方，不在正确的位置

### ISSUE THREAD

**Issue by google88888888** [antvis/XFlow#392]
### 问题描述

ios手机任何浏览器，查看xflow自定义节点布局，自定义节点都会跑到屏幕左上方，不在正确的位置

### 重现链接

ios手机

### 重现步骤

ios手机任何浏览器，查看xflow自定义节点布局，自定义节点都会跑到屏幕左上方，不在正确的位置

### 预期行为

ios手机任何浏览器，查看xflow自定义节点布局，自定义节点都会跑到屏幕左上方，在正确的位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by lyp000119** [comment]
建议不要用xflow了，感觉没有人维护了
