### ISSUE TITLE
支持新版的 x6

### ISSUE THREAD

**Issue by LukerSpringtree** [antvis/XFlow#413]
### 描述你想申请的功能

<img width="867" alt="image" src="https://github.com/antvis/XFlow/assets/9697295/c34e553c-80cc-4943-9877-838694021770">
现在的依赖是 x6  v1版本
现在有v2版本了

### 描述你想要的解决方案

希望能支持 x6v2 版本

### 描述你所考虑的替代方案

希望能支持 x6v2 版本

**Comment by hyzx86** [comment]
顶起来，同求 支持 X6V2

**Comment by kemisstep** [comment]
顶起来，同求 支持 X6V2

**Comment by wozien** [comment]
顶起来，同求 支持 X6V2

**Comment by TianQingshuai** [comment]
同问有相关计划吗？
