### ISSUE TITLE
Enable Github Discussions for XFlow

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/XFlow#42]
Hi XFlow team,
I was wondering if you would be open to enabling the Github Discussion's feature for the this repository.

### Motiviation For Change
- Once the Github Discussion's tab is enabled, people can post their questions and that would help with finding questions and solutions more easily for the community.
- G6 and Graphin repositories recently enabled Discussions 
   - https://github.com/antvis/G6/issues/3363

How to enable Discussions for this repository can be found here:
- https://docs.github.com/en/discussions

Example of what Github Discussion's look like when enabled
- `react-query`'s github discussion's - https://github.com/tannerlinsley/react-query/discussions
- [`@antv/graphin` - Graphin Github Discussion's tab is enabled](https://github.com/antvis/Graphin/discussions)
   ![CleanShot 2021-12-12 at 11 26 19@2x](https://user-images.githubusercontent.com/6743796/145726568-36b7a522-1d5d-4a5d-81b9-d750c803f7a3.png)
   
   
## Related:
- #43

**Comment by cliffordfajardo** [comment]
@NewByVector

**Comment by lyn-boyu** [comment]
@cliffordfajardo  thanks for your advise
