### ISSUE TITLE
CanvasToolbar中toolbarConfig.setCustomToolbarRender自定义渲染如何使用IGraphCommandService 

### ISSUE THREAD

**Issue by wh1teYu** [antvis/XFlow#420]
### 描述你想申请的功能

CanvasToolbar中toolbarConfig.setCustomToolbarRender自定义渲染如何使用IGraphCommandService 

### 描述你想要的解决方案

CanvasToolbar中toolbarConfig.setCustomToolbarRender自定义渲染如何使用IGraphCommandService 

### 描述你所考虑的替代方案

CanvasToolbar中toolbarConfig.setCustomToolbarRender自定义渲染如何使用IGraphCommandService

### 屏幕截图或视频

 // 自定义操作栏
  toolbarConfig.setCustomToolbarRender(
    async (modelService, updateComponent) => {
      const model = await MODELS.SELECTED_NODES.getModel(modelService)

      model.watch((nodes) => {
        let Toolbar = (props) => {
          console.log('props', props)

          const [edit, setEdit] = useState(false)
          const [form] = Form.useForm()

          const fields = [
            {
              key: 'type',
              label: '规则类别',
              value: '筛选类规则',
              disabled: true,
              style: { width: 110 },
            },
            {
              key: 'name',
              label: '规则名称',
              value: '产品推荐展示规则',
              disabled: !edit,
              style: { width: 156 },
            },
            {
              key: 'remark',
              label: '规则说明',
              value: '针对不同客群推荐展示不同产品…',
              disabled: !edit,
              style: { width: 266 },
            },
          ]

          // 保存基本信息
          const handleSubmitBaseInfo = (values) => {
            console.log('values', values)
          }

          // 保存
          const handleSubmit = () => {
            console.log('props', props)
            console.log(XFlowGraphCommands.SAVE_GRAPH_DATA, '999')
          }

          return (
            <div className={cls(styles['custom-toolbar'])}>
              <Form form={form} onFinish={handleSubmitBaseInfo}>
                {fields.map((field) => {
                  return (
                    <FormItem label={field.label} name={field.key}>
                      <Input
                        value={field.value}
                        defaultValue={field.value}
                        disabled={field.disabled}
                        style={field.style}
                      />
                    </FormItem>
                  )
                })}
                {edit ? (
                  <>
                    <Button type="primary" htmlType="submit">
                      确定
                    </Button>
                    <Button
                      className={cls(styles['ml-8'])}
                      onClick={() => {
                        setEdit(false)
                        form.resetFields()
                      }}
                    >
                      取消
                    </Button>
                  </>
                ) : (
                  <>
                    <FormOutlined onClick={() => setEdit(true)} />
                    <Button className={cls(styles['bakck'])}>返回</Button>
                    <Button
                      type="primary"
                      className={cls(styles['submit'])}
                      onClick={handleSubmit}
                    >
                      保存
                    </Button>
                    <Button
                      type="primary"
                      icon={<FolderOutlined />}
                      className={cls(styles['audit'])}
                    >
                      保存并提交审核
                    </Button>
                  </>
                )}
              </Form>
            </div>
          )
        }
        updateComponent(Toolbar)
      })
      return null
    }
  )
  
  这段代码，我需要在保存的时候，调用IGraphCommandService，调用画布的保存功能

**Comment by TSjianjiao** [comment]
用`useXFlowApp`获取`app`实例，然后`app.commandService.executeCommand`。可以[参考这个文章](https://juejin.cn/post/7237240999244152869)
