### ISSUE TITLE
左右布局水平连接线不直

### ISSUE THREAD

**Issue by wozien** [antvis/XFlow#424]
### Describe the bug

左右布局水平连接线不直

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-a28g1p?file=src%2FApp.tsx
### Steps to Reproduce the Bug or Issue

官方提供的demo就可以重现：
https://xflow.antv.vision/docs/tutorial/solutions/dag#%E6%94%AF%E6%8C%81%E5%B7%A6%E5%8F%B3%E5%B8%83%E5%B1%80

<img width="660" alt="image" src="https://github.com/antvis/XFlow/assets/17634819/9f0c219b-0fcd-47ae-ad53-7d7ce7cd53fa">

### Expected behavior

水平线是直的

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Jzhenli** [comment]
你好，这个例程怎么单独运行的？在codesandbox里显示有错误 @wozien

**Comment by wozien** [comment]
> 你好，这个例程怎么单独运行的？在codesandbox里显示有错误 @wozien

https://stackblitz.com/edit/vitejs-vite-a28g1p?file=src%2FApp.tsx 这里复现的demo哈。还有我发现可能是CanvasNodePortTooltip插件的问题，我不用这个插件是ok的
<img width="433" alt="image" src="https://github.com/antvis/XFlow/assets/17634819/2ea9ade8-415b-4bf3-bd19-814b2b908ece">
