### ISSUE TITLE
请问这框架还有人维护么？

### ISSUE THREAD

**Issue by yxf18** [antvis/XFlow#430]
### 问题描述

如题所示，准备用这个方案，害怕有坑没人维护，，，文档都不全
![image](https://github.com/antvis/XFlow/assets/50571024/5a8fce36-2e7b-46fe-8f59-21bc0421c61e)

### 重现链接

https://xflow.antv.vision/

### 重现步骤

![image](https://github.com/antvis/XFlow/assets/50571024/88af9e9c-16c6-4b88-9dcc-b5e33d327354)

### 预期行为

有人维护，别烂尾

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
1.x 确实不再维护了，2.0 版本已经开发完成，可以直接基于  2.0 开发。

**Comment by huo708709** [comment]
> 1.x 因为复杂度高，上手成本高等原因，不再维护了，2.0 版本已经开发完成，可以直接使用 2.0 版本。2.0 版本的特性如下：
> 
> **极简易用**。提供更贴合 React 组件的使用方式，去掉所有复杂概念，像使用 antd 组件一样使用图编辑组件。 **配套齐全**。内置常用图编辑配套组件，上层提供 DAG 图、ER 图、流程图等成熟解决方案。
> 
> 希望 2.0 版本能解决你的业务问题。

没有相关文档呢，不知道咋使用！！！

**Comment by linhf123** [comment]
@NewByVector 有没有钉钉群 来个二维码

**Comment by jiang-zhong-xi** [comment]
2.0版本的release什么时候发布呢？

**Comment by jiang-zhong-xi** [comment]
> 2.0版本的release什么时候发布呢？

@NewByVector
