### ISSUE TITLE
能否支持vue框架?

### ISSUE THREAD

**Issue by 37-Ricardo** [antvis/XFlow#437]
### 描述你想申请的功能

想要能够支持vue2/3,或者出一个简单的示例代码文档

### 描述你想要的解决方案

目前的存量项目为vue项目，但是XFLOW没有看到相关的文档支持，是否支持vue2/3项目，或者出一份简单的基于vue项目的示例代码

### 描述你所考虑的替代方案

无

**Comment by 37-Ricardo** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正忙，无法亲自回复你的邮件。我将在解决手头的事情后，尽快给你回复。

**Comment by NewByVector** [comment]
暂时只支持 react 。

**Comment by lloydzhou** [comment]
vue也可以参照xflow写一个版本
