### ISSUE TITLE
XFlow 2.x  Cannot read properties of null (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by Ariel-Lau** [antvis/XFlow#439]
### 问题描述

XFlow 2.x：未使用 XFlow 的 store管理状态，自定义状态管理，节点更新时会报：Uncaught TypeError: Cannot read properties of null (reading 'hasOwnProperty') 错误

### 重现链接

-

### 重现步骤

不使用 XFlow 的 store 状态管理

### 预期行为

不报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by NewByVector** [comment]
https://github.com/antvis/XFlow/pull/441
