### ISSUE TITLE
edge id问题

### ISSUE THREAD

**Issue by xuxingeren** [antvis/XFlow#44]
视图生成的edge id并不是uuid，而是[object Object]:xxxxxx-[object Object]:xxxx，这会导致以下情况出现不能正常获取edge

XFlow的onLoad实践里获取
```
const onLoad = async (app) => {
  const graph = await app.getGraphInstance()
  graph.on('edge:connected', ({ isNew, edge }) => {
      // 直接获取edge，此时edge的id是uuid，能正常删除
      // graph.removeEdge(edge.id)
      setTimeout(() => {
          // 删除失败，此时获取的还是uuid，但是通过addEdge的hooks拿到的edge是[object Object]:xxxxxx-[object Object]:xxxx格式的，也就是edge实际上连线完成后变化了？
          graph.removeEdge(edge.id)
      }, 1000)
    }) 
}
```

**Comment by lyn-boyu** [comment]
可以提供一个codesandbox来说明问题么？

**Comment by xuxingeren** [comment]
> 

关注点在App.tsx里打印的，这是[示例链接](https://codesandbox.io/s/zealous-brahmagupta-mt7vg)

**Comment by xuxingeren** [comment]
> 可以提供一个codesandbox来说明问题么？



> 可以提供一个codesandbox来说明问题么？

关注点在App.tsx里打印的，这是[示例链接](https://codesandbox.io/s/zealous-brahmagupta-mt7vg)

**Comment by lyn-boyu** [comment]
感谢你的codesandbox。
问题已经定位连线时 edge:connected 生成的临时edge会被删除，xflow 会获取临时edge的元数据（source/target）并通过执行addEdge的命令来完成添加。[object Object]:的情况是source在flow的场景下是一个对象结构，导致拼接edge id时出错，这里我修复下，估计今天发布。

**Comment by lyn-boyu** [comment]
https://github.com/antvis/XFlow/pull/57 
更新到1.0.17可以解决这个问题
