### ISSUE TITLE
Lazy loading node relations.

### ISSUE THREAD

**Issue by hsingh-ds** [antvis/XFlow#445]
### Describe the feature you'd like to request

I want to give the user ability to load the relation of specific node. User will click on the node and the data for that node will be fetched on demand instead of fetching all graph data on first load.

### Describe the solution you'd like

There should be a way to expand the graph from a specific node.

### Describe alternatives you've considered

I have not implemented the alternatives. I am planning to use the react context and access that from graph nodes to load the data for specific node and append it to the graph data.

**Comment by NewByVector** [comment]
This is business logic and has nothing to do with xflow itself.
