### ISSUE TITLE
动态创建边时不指定 id，更新时找不到边导致更新失败

### ISSUE THREAD

**Issue by baizn** [antvis/XFlow#451]
### Describe the bug

动态创建边时不指定 id，更新时找不到对应的边

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1. 动态添加边，不指定 id
2. 使用 updateEdge 更新添加的这条边

### Expected behavior

能正常更新

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by NewByVector** [comment]
更新到 2.0.4.
