### ISSUE TITLE
docs: 更新 xflow 2.0 官网

### ISSUE THREAD

**Issue by NewByVector** [antvis/XFlow#453]
### Describe the feature you'd like to request

更新 xflow 2.0 官网

### Describe the solution you'd like

更新 xflow 2.0 官网

### Describe alternatives you've considered

更新 xflow 2.0 官网

**Comment by ableF** [comment]
您好打扰了，请问咱有没有对外的钉钉群或者微信群呢。我关注了公众号并加了对应的个人号但是没有人拉我进群，官网的钉钉群二维码也已经失效。我现在遇到了xflow使用的性能问题，想请你们帮忙看看是否有优化手段的最佳实践。

**Comment by NewByVector** [comment]
新版本官网地址：https://x6.antv.antgroup.com/xflow/guide/introduction
