### ISSUE TITLE
2.0 release什么时候发布呢

### ISSUE THREAD

**Issue by jiang-zhong-xi** [antvis/XFlow#460]
### 描述你想申请的功能

2.0 release

### 描述你想要的解决方案

2.0版本什么时候可以用啊，我看仓库只有1.0版本的release，npm包也只有1.0版本的，请问2.0版本计划什么时候发布？

### 描述你所考虑的替代方案

如果我自己构建2.0版本的话现在的代码可用度高吗？

**Comment by coderyqh** [comment]
文档也是老版本的，什么时候能够更新

**Comment by jiang-zhong-xi** [comment]
@NewByVector 有没有个具体的发布计划呢？

**Comment by stewie146** [comment]
这个还有人维护吗？
