### ISSUE TITLE
xflow不支持x6 graph的interacting配置

### ISSUE THREAD

**Issue by mya12321** [antvis/XFlow#464]
### 问题描述

xflow不支持x6 graph的interacting配置

### 重现链接

https://x6.antv.antgroup.com/api/model/interaction#%E9%99%90%E5%88%B6

### 重现步骤

xflow源码:
![image](https://github.com/antvis/XFlow/assets/14355408/8614df1b-42fc-40d5-a652-2c357ac5c4db)

### 预期行为

XFlowGraph增加interacting配置

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Edge]
- XFlow 版本: [2.0.4]

**Comment by zhangtinghang** [comment]
x6 graph的interacting配置被xflow封装成了readonly。
![image](https://github.com/antvis/XFlow/assets/21197164/2b7af157-c0be-424f-961e-62644b2490c4)

**Comment by mya12321** [comment]
可是我希望精准的控制交互, 比如interacting.edgeLabelMovable, 而不是简单粗暴的readonly
