### ISSUE TITLE
Xflow如何使用连接桩的tooltip功能呢？

### ISSUE THREAD

**Issue by 583849487** [antvis/XFlow#473]
### 问题描述

看了很多实例，都是x6的玩法，但是xflow中该怎么对连接桩进行tooltip呢？我找到了连接桩的useGraphEvent('node:port:mouseenter'事件，想配合ReactDOM.render去实现，但是还是不能渲染https://x6.antv.vision/zh/examples/node/tool#port-tooltip

### 重现链接

https://x6.antv.vision/zh/examples/node/tool#port-tooltip

### 重现步骤

https://x6.antv.vision/zh/examples/node/tool#port-tooltip

### 预期行为

xflow中对连接桩的鼠标移入事件进行tooltip

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by 583849487** [comment]
至今未解决哦，官网demo使用tooltip功能也报错。。。

**Comment by 583849487** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here. If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not-stale" to keep this issue open!
> 
> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [contribute](https://github.com/antvis/X6/blob/master/CONTRIBUTING.md) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the AntV community! 💪💯

not-stale

**Comment by NewByVector** [comment]
这个例子：https://x6.antv.antgroup.com/zh/examples/node/tool/#port-tooltip
