### ISSUE TITLE
xflow这个报错怎么解决？ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by 583849487** [antvis/XFlow#474]
### 问题描述

只要渲染画布区的节点就会有这个报错，是什么原因呢？

### 重现链接

无

### 重现步骤

![image](https://github.com/antvis/XFlow/assets/77159352/b9d91a39-5f77-44ea-a506-fe7c7bfb4907)

### 预期行为

解决报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]

**Comment by vok123** [comment]
渲染react组件时因为xflow引用的`@antv/x6-react-shape`版本是2.0.8，该版本是react 18以下使用的。可以在项目package.json中加入
```json 
"resolutions": {
    "@antv/x6-react-shape": "2.2.3"
}
```
清理编译缓存重新再试试

**Comment by 583849487** [comment]
通过@antv/x6-react-shape的版本为2.2.3，已解决报错。
