### ISSUE TITLE
@antv/xflow2.x bug

### ISSUE THREAD

**Issue by BrightStarrySky** [antvis/XFlow#475]
### 问题描述

@antv/xflow2.x 版本在  umi/max  4.3.1  以及  react 18.3.1 版本中 ts  报错 ，并且2.x 文档中的demo 内容在项目中无法正常使用

### 重现链接

https://codesandbox.io/s/misty-sunset-grvzh3?file=/cmd-extensions/cmd-rename-node-modal.tsx

### 重现步骤

运行项目示例

### 预期行为

正常执行业务

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- XFlow 版本: [1.28.2 ... ]
windows11

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/XFlow/assets/34825195/536bd7a5-2a1b-48c3-913a-333769a171b5)

**Comment by BrightStarrySky** [comment]
keep-open

**Comment by NewByVector** [comment]
你这个看起来是 1.x 版本的代码

**Comment by BrightStarrySky** [comment]
> 你这个看起来是 1.x 版本的代码

可是文档中示例就是这个哦，没看到有版本区分啊, react 18中应该使用哪个版本呢,

**Comment by NewByVector** [comment]
2.x 的文档在这里 https://x6.antv.antgroup.com/xflow/guide/introduction。
