### ISSUE TITLE
渲染react组件时因为xflow引用的`@antv/x6-react-shape`版本是2.0.8，该版本是react 18以下使用的。

### ISSUE THREAD

**Issue by vok123** [antvis/XFlow#476]
### 问题描述

渲染react组件时因为xflow引用的`@antv/x6-react-shape`版本是2.0.8，该版本是react 18以下使用的。建议升级一下或者怎么处理一下， 不然react 18+ 是没办渲染自定义组件的， 感谢付出。
@antv/x6-react-shape文档解释地址：https://x6.antv.antgroup.com/tutorial/intermediate/react

### 重现链接

暂无

### 重现步骤

1. react 版本使用18+, xflow使用2.1.10；
2. 使用了useDnd, 将自定义的react组件拖进graph中；
3. 无法将组件渲染出来

### 预期行为

能将将组件渲染出来

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- XFlow 版本: [2.1.10]

**Comment by NewByVector** [comment]
@antv/x6-react-shape 2.0.8 是兼容 react18+的，有例子可以看下吗？

**Comment by l704863851** [comment]
> @antv/x6-react-shape 2.0.8 是兼容 react18+的，有例子可以看下吗？

同样的问题，这是例子 https://codesandbox.io/p/sandbox/yxwz9r 可在控制台看到报错信息

![image](https://github.com/user-attachments/assets/5cc7ab20-6b88-42fc-9445-6977cb22d6b6)
