### ISSUE TITLE
Support directly using a React component for icons in `ToolbarItemOptions` / `ToolbarItemOptions` 设置图标支持直接引用 React 组件

### ISSUE THREAD

**Issue by tonywu6** [antvis/XFlow#7]
### Current behavior 当前行为

When configuring the toolbar and setting the icons for each toolbar items, one must first register the icon's React component constructor with an `IconStore` singleton, and then provide the corresponding registered key as a string to the options object via the `iconName` field.

现在在设置 Toolbar 工具栏之按键图标时，需要先在 IconStore 注册每个图标，给每个图标提供一个 key，然后才在 Toolbar 设置项里通过 `iconName` 引用之前注册的 key.

```ts
// ...
import { IconStore } from '@antv/xflow';

const MyIcon = () => <div />;
IconStore.set('my-icon', MyIcon);

// ...
{
    items: [{
        // ...
        iconName: 'my-icon',
        // ...
    }],
    // ...
}
```

### Possible alternative 其他方法

Pass a React component constructor or a function returning a React component instance to the config instead.

直接在设置项里提供 React 组件或者最终返回 React 组件的函数。

```tsx
const MyIcon = () => <div />;
{
    items: [{
        icon: MyIcon,
    }],
}
```

### Additional context 讨论

Using a singleton registry to manage icons seems rather redundant, compared to referencing the icon component themselves directly (are there any future designs that would justify using a singleton?)

Using a string to indicate which icon also bypasses the compiler's guarantee that names must be defined (especially with TypeScript): a typo in the registered key or in the config would cause the icon to fail to render at runtime, because the compiler can no longer reliably tell that the icon with name `'my-icon'` is in fact available for use.

目前来看通过 `IconStore` 来事先注册图标的方式似乎有些繁琐，不知道是不是之后有其他的功能需要这样的设计？

以字符串的方式引用图标也意味着编译器编译时没有办法检查图标是否有正确注册，若注册时或者生成工具栏设置时出现错别字，则图标会渲染失败而且要在运行时才能发现。

**Comment by lyn-boyu** [comment]
agree 
1.  we can improve this by adding a property key in ToolbarItemOptions: "icon".
2.  the current design is not redundant if your config is stored in your backend database table. 
--------------------
同意
1. 我们可以在ToolbarItemOptions中添加一个icon的字段来支持组件的配置方式
2. 当前的设计是为了兼容会把toolbar配置储存在后端db的场景，icon组件不能被json序列化。
