### ISSUE TITLE
ER 建模解决方案 链接桩精确到字段级别

### ISSUE THREAD

**Issue by yqwoe** [antvis/XFlow#82]
### ER  连接桩精确到字段级别
* 当无法确定附属表的外键时候
* 需要用户自定义外键连接
* 并且source和target数据最好携带 表和链接桩的具体信息
[参考X6 ER](https://x6.antv.vision/zh/examples/showcase/practices#er)

### ER  连接桩精确到字段级别
* 当无法确定附属表的外键时候
* 需要用户自定义外键连接
* 并且source和target数据最好携带 表和链接桩的具体信息
[参考X6 ER](https://x6.antv.vision/zh/examples/showcase/practices#er)

### 描述你所考虑的替代方案

目前我是是用gojs-react实现的er图，但是整体体验并不好，还有商业授权，扩展很麻烦，想使用xflow-er来代替。

**Comment by lyn-boyu** [comment]
@gujinyue1010  please check it out

**Comment by yqwoe** [comment]
大佬，这个需求有进展吗

**Comment by yqwoe** [comment]
大佬们，需求有进展吗，项目中需要用到
